// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/spotify/spotify.proto

package go_micro_service_spotify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Spotify service

func NewSpotifyEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Spotify service

type SpotifyService interface {
	RootRedirect(ctx context.Context, in *RedirectRequest, opts ...client.CallOption) (*RedirectResponse, error)
	Callback(ctx context.Context, in *CallbackRequest, opts ...client.CallOption) (*CallbackResponse, error)
	Save(ctx context.Context, in *SaveRequest, opts ...client.CallOption) (*SaveResponse, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Spotify_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Spotify_PingPongService, error)
}

type spotifyService struct {
	c    client.Client
	name string
}

func NewSpotifyService(name string, c client.Client) SpotifyService {
	return &spotifyService{
		c:    c,
		name: name,
	}
}

func (c *spotifyService) RootRedirect(ctx context.Context, in *RedirectRequest, opts ...client.CallOption) (*RedirectResponse, error) {
	req := c.c.NewRequest(c.name, "Spotify.RootRedirect", in)
	out := new(RedirectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spotifyService) Callback(ctx context.Context, in *CallbackRequest, opts ...client.CallOption) (*CallbackResponse, error) {
	req := c.c.NewRequest(c.name, "Spotify.Callback", in)
	out := new(CallbackResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spotifyService) Save(ctx context.Context, in *SaveRequest, opts ...client.CallOption) (*SaveResponse, error) {
	req := c.c.NewRequest(c.name, "Spotify.Save", in)
	out := new(SaveResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spotifyService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Spotify_StreamService, error) {
	req := c.c.NewRequest(c.name, "Spotify.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &spotifyServiceStream{stream}, nil
}

type Spotify_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type spotifyServiceStream struct {
	stream client.Stream
}

func (x *spotifyServiceStream) Close() error {
	return x.stream.Close()
}

func (x *spotifyServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *spotifyServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *spotifyServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *spotifyServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *spotifyService) PingPong(ctx context.Context, opts ...client.CallOption) (Spotify_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Spotify.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &spotifyServicePingPong{stream}, nil
}

type Spotify_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type spotifyServicePingPong struct {
	stream client.Stream
}

func (x *spotifyServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *spotifyServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *spotifyServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *spotifyServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *spotifyServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *spotifyServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Spotify service

type SpotifyHandler interface {
	RootRedirect(context.Context, *RedirectRequest, *RedirectResponse) error
	Callback(context.Context, *CallbackRequest, *CallbackResponse) error
	Save(context.Context, *SaveRequest, *SaveResponse) error
	Stream(context.Context, *StreamingRequest, Spotify_StreamStream) error
	PingPong(context.Context, Spotify_PingPongStream) error
}

func RegisterSpotifyHandler(s server.Server, hdlr SpotifyHandler, opts ...server.HandlerOption) error {
	type spotify interface {
		RootRedirect(ctx context.Context, in *RedirectRequest, out *RedirectResponse) error
		Callback(ctx context.Context, in *CallbackRequest, out *CallbackResponse) error
		Save(ctx context.Context, in *SaveRequest, out *SaveResponse) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Spotify struct {
		spotify
	}
	h := &spotifyHandler{hdlr}
	return s.Handle(s.NewHandler(&Spotify{h}, opts...))
}

type spotifyHandler struct {
	SpotifyHandler
}

func (h *spotifyHandler) RootRedirect(ctx context.Context, in *RedirectRequest, out *RedirectResponse) error {
	return h.SpotifyHandler.RootRedirect(ctx, in, out)
}

func (h *spotifyHandler) Callback(ctx context.Context, in *CallbackRequest, out *CallbackResponse) error {
	return h.SpotifyHandler.Callback(ctx, in, out)
}

func (h *spotifyHandler) Save(ctx context.Context, in *SaveRequest, out *SaveResponse) error {
	return h.SpotifyHandler.Save(ctx, in, out)
}

func (h *spotifyHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.SpotifyHandler.Stream(ctx, m, &spotifyStreamStream{stream})
}

type Spotify_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type spotifyStreamStream struct {
	stream server.Stream
}

func (x *spotifyStreamStream) Close() error {
	return x.stream.Close()
}

func (x *spotifyStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *spotifyStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *spotifyStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *spotifyStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *spotifyHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.SpotifyHandler.PingPong(ctx, &spotifyPingPongStream{stream})
}

type Spotify_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type spotifyPingPongStream struct {
	stream server.Stream
}

func (x *spotifyPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *spotifyPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *spotifyPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *spotifyPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *spotifyPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *spotifyPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
